language: scala
scala:
- 2.10.4
- 2.11.2
jdk:
- oraclejdk7
branches:
  only:
  - master
services:
- mongodb
notifications:
  email:
    recipients:
    - platform-engineering@digital.cabinet-office.gov.uk
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: Uq6mp4uqcxFl3CuCH42cKm4OBRt2KdwWIekFBDM7ETeakx5PVw2hafhzoyh2s1zzyDyM0i0oL+OooL7XRjyl8ZtzHV3USyLZxeCBdUbsLxhifsSlwaU7IUf0rhMpM9nB6dWw3N8h8V0HpcS/wHda1KA2Par/chdqCDQ38NFaWhM=
  - secure: dJo8bSq5tJZZSUaTyEXEdUP+kWIwBwbn0upPraEvA+LSey61FrRrqPTQfE+rYX76SDdLPLn6cJssqCHtxOgoQOynUumT3t6w3o9+JQLxKvKlseTYs1RZoSwhsib6ZkiS5QREOlfQfSN4eb/Ft0TO8/MgB/GMy2vpz6/1bE1Zze4=
